services:
  app:
    image: steamapp:dev
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: steamapp_user
      POSTGRES_DB: steamapp
    volumes:
      - ../db_data:/var/lib/postgresql/data:rw
    ports:
      - "8000:5432"

volumes:
  db_data:
